#you need to enter your data sequentially
print("Enter your name")
name = input()
print("Enter your surname")
surname = input()
print("Enter your phone number")
number = input()
print("Enter your street")
street = input()
print("Enter your street number")
st.number = input()
print("Enter your apartment number")
ap.number = input()
print("Enter your city")
city = input()
print("Enter your index")
index = input()
print("Enter your country")
country = input()